POST http://localhost:3333/courses
Content-Type: application/json

{
 "title": "Curso bolado de como progamar cagando"
}

###

GET http://localhost:3333/courses


###

GET http://localhost:3333/courses/f1751f20-11f2-472a-9598-64327c580db0

