POST http://localhost:3333/courses
Content-Type: application/json

{
 "title": "o 2"
}

###

GET http://localhost:3333/courses


###

GET http://localhost:3333/courses/e6ac39db-9a30-4908-a4ab-076a6f656143

